-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 12:33:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culdampolla` DEFAULT CHARACTER SET utf8 ;
USE `culdampolla` ;

-- -----------------------------------------------------
-- Table `culdampolla`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`ulleres` (
  `id_ulleres` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `vidre_dret` VARCHAR(45) NOT NULL,
  `vidre_esquerre` VARCHAR(45) NOT NULL,
  `tipus_muntura` VARCHAR(45) NOT NULL,
  `color_muntura` VARCHAR(45) NOT NULL,
  `color vidre` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  PRIMARY KEY (`id_ulleres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`proveidor` (
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `número` INT NOT NULL,
  `pis` VARCHAR(20) NOT NULL,
  `porta` VARCHAR(20) NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codig postal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT(10) NOT NULL,
  `fax` INT NULL,
  `ulleres_id_ulleres` INT NOT NULL,
  UNIQUE INDEX `porta_UNIQUE` (`porta` ASC) VISIBLE,
  INDEX `fk_proveidor_ulleres_idx` (`ulleres_id_ulleres` ASC) VISIBLE,
  CONSTRAINT `fk_proveidor_ulleres`
    FOREIGN KEY (`ulleres_id_ulleres`)
    REFERENCES `culdampolla`.`ulleres` (`id_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`Clients` (
  `id_clients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adressa_postal` VARCHAR(10) NOT NULL,
  `telefon` INT NULL,
  `mail` VARCHAR(255) NULL,
  `data_registre` DATETIME NULL,
  `client_recomana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clients`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`venedors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`venedors` (
  `id_venedor` INT NOT NULL AUTO_INCREMENT,
  `nom_complet` VARCHAR(45) NOT NULL,
  `venta_import` VARCHAR(45) NOT NULL,
  `data_venta` DATETIME NOT NULL,
  PRIMARY KEY (`id_venedor`),
  UNIQUE INDEX `nom_complet_UNIQUE` (`nom_complet` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`Clients_has_ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`Clients_has_ulleres` (
  `Clients_id_clients` INT NOT NULL,
  `ulleres_id_ulleres` INT NOT NULL,
  PRIMARY KEY (`Clients_id_clients`, `ulleres_id_ulleres`),
  INDEX `fk_Clients_has_ulleres_ulleres1_idx` (`ulleres_id_ulleres` ASC) VISIBLE,
  INDEX `fk_Clients_has_ulleres_Clients1_idx` (`Clients_id_clients` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_has_ulleres_Clients1`
    FOREIGN KEY (`Clients_id_clients`)
    REFERENCES `culdampolla`.`Clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_has_ulleres_ulleres1`
    FOREIGN KEY (`ulleres_id_ulleres`)
    REFERENCES `culdampolla`.`ulleres` (`id_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`Clients_has_venedors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`Clients_has_venedors` (
  `Clients_id_clients` INT NOT NULL,
  `venedors_id_venedor` INT NOT NULL,
  PRIMARY KEY (`Clients_id_clients`, `venedors_id_venedor`),
  INDEX `fk_Clients_has_venedors_venedors1_idx` (`venedors_id_venedor` ASC) VISIBLE,
  INDEX `fk_Clients_has_venedors_Clients1_idx` (`Clients_id_clients` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_has_venedors_Clients1`
    FOREIGN KEY (`Clients_id_clients`)
    REFERENCES `culdampolla`.`Clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_has_venedors_venedors1`
    FOREIGN KEY (`venedors_id_venedor`)
    REFERENCES `culdampolla`.`venedors` (`id_venedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
